# Generated by Django 4.2.3 on 2023-07-09 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Administrador",
            fields=[
                (
                    "rut",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=255)),
                ("contrasena", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Alumno",
            fields=[
                (
                    "rut",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=255)),
                ("contrasena", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Bodeguero",
            fields=[
                (
                    "rut",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=255)),
                ("contrasena", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Carrera",
            fields=[
                ("carrera_id", models.IntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                ("curso_id", models.IntegerField(primary_key=True, serialize=False)),
                ("grado", models.IntegerField()),
                ("letra", models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="EstadoSolicitud",
            fields=[
                ("estado_id", models.IntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Herramienta",
            fields=[
                (
                    "herramienta_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("stock", models.IntegerField()),
                ("medida_stock", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "rut",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=255)),
                ("contrasena", models.CharField(max_length=255)),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.carrera"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Solicitud",
            fields=[
                (
                    "solicitud_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("fecha_solicitud", models.DateTimeField()),
                ("fecha_entrega", models.DateTimeField()),
                ("fecha_devolucion", models.DateTimeField()),
                (
                    "alumno_rut",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.alumno"
                    ),
                ),
                (
                    "estado_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.estadosolicitud",
                    ),
                ),
                (
                    "profesor_rut",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.profesor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolicitudHerramienta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField()),
                (
                    "herramienta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.herramienta",
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.solicitud"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolicitudAlumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alumno_rut",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.alumno"
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.solicitud"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="alumno",
            name="carrera",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.carrera"
            ),
        ),
        migrations.AddField(
            model_name="alumno",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.curso"
            ),
        ),
    ]
