# Generated by Django 4.2.3 on 2023-10-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_solicitud_fecha_devolucion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumno",
            name="carrera",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="curso",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="profesor",
            name="carrera",
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name="Carrera",
        ),
        migrations.DeleteModel(
            name="Curso",
        ),
    ]
