# Generated by Django 4.2.3 on 2023-10-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_alumno_carrera_alter_alumno_curso_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herramienta",
            name="herramienta_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
