# Generated by Django 4.2.3 on 2023-10-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_herramienta_herramienta_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="herramienta",
            name="lvl_stock",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
