# Generated by Django 4.2.3 on 2023-10-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_alumno_contrasena"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumno",
            name="contrasena",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
